services:
    distcc:
        container_name: distcc-server
        image: distcc-server:latest
        environment: 
            - NETWORK=192.168.178.0/24
            - JOBS=14
        ports:
            - 3632:3632
        user: distccd
